version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=src.settings.dev
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    #tty: true #fixes the react-scripts 3.4.1 bug
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
